### ISSUE TITLE
Compatibility with nnn file manager on macOS

### ISSUE THREAD

**Issue by carlca** [aaronjanse/3mux#64]
* macOS 10.14.6

Not so much an issue, more a word of thanks! I tried out the command line file manager `nnn` yesterday and it didn't seem to work under `3Mux` - the cursor keys failed to respond. I tried again just now, after running `go get -u github.com/aaronjanse/3mux` to update, and it works! 
Very cool 😉

**Comment by aaronjanse** [comment]
> the cursor keys failed to respond. I tried again just now, after running `go get -u github.com/aaronjanse/3mux` to update, and it works!

Oh awesome! I changed the input processing system in `v0.2`, so that's probably what fixed it.

> Very cool :wink:

Thank you!

I'll close this issue (because it's fixed now), but thank you for opening it; this issue will be helpful to people running `nnn` using an old version of `3mux` (e.g. from a package manager). Cheers!
